---
title: ""
---

## Research

### Peer-Reviewed Articles

<ol reversed>
<li> Justwan, Florian, Jeffrey Berejikian, and [**Shawn Mazdeyasnan**]{.underline}. 2025. “Deserving Special Treatment? The Effect of Psychological Entitlement on Support for International Law.” *Foreign Policy Analysis* 21(2). doi:[10.1093/fpa/oraf004](https://doi.org/10.1093/fpa/oraf004). </li>
</ol>

```{=html}
<!--
### Articles in Revision
-->
```
### Works in Progress

<ol reversed>
<li> "Do Ethnic Civil Wars Produce More Indiscriminate Violence?: An Analysis" </li>
<li> "Disaggregating Forms of Election Violence: Elections and the Use of Torture and Ill-Treatment" </li>
<li> "'Peace' After Peacekeeping: Post-Peacekeeping Periods and One-Sided Violence" </li>
</ol>

<br>

### Research Experience

#### University of Georgia

##### *Department of International Affairs Graduate Research Assistant*

-   Jeffrey Berejikian (Spring 2025, Fall 2024, Summer 2024, Spring 2024, Fall 2023, Fall 2022) <br> <br>

##### *Center for the Study of Global Issues (GLOBIS) Graduate Research Assistant*

-   K. Chad Clay (Spring 2025, Fall 2024, Spring 2024, Fall 2023, Summer 2023, Spring 2023) <br> <br>

#### Human Rights Measurement Initiative (HRMI)

##### *Research Assistant*

-   K. Chad Clay (Spring 2025, Fall 2024, Summer 2024, Spring 2024, Fall 2023, Summer 2023, Spring 2023)
