---
title: ""
---

## Teaching

### [**University of Georgia**]{.underline}

#### ***Department of International Affairs***

##### [*Instructor of Record*]{.underline}

-   INTL 4295 War and Human Security -  [(Syllabus)](https://shawnmazdey.github.io/external_docs/Syllabi/INTL_4295_Syllabus_Fall_2025.pdf)

    -   Fall 2025 <br> <br>

##### [*Teaching Assistant*]{.underline}

-   INTL 3200 Introduction to International Relations

    -   Maryann Gallagher: Fall 2023, Spring 2023, Fall 2022

    -   Gulçan Saglam: Spring 2023

-   INTL 4250 American Foreign Policy

    -   Maryann Gallagher: Spring 2025

-   INTL 4370 Middle Eastern Politics

    -   Eli Sperling: Summer 2025

-   INTL 4620 Human Rights

    -   K. Chad Clay: Spring 2026

-   INTL 4630 Population, Immigration, and Politics

    -   Gulçan Saglam: Spring 2023

-   INTL 4960R Faculty-Mentored Undergraduate Research I

    -   Eli Sperling: Summer 2025 <br> <br>

### [**University of Michigan**]{.underline}

#### ***Inter-University Consortium for Social and Political Research (ICPSR) Summer Program***

##### [*Teaching Assistant*]{.underline}

-   Maximum Likelihood Estimation II

    -   Desmond Wallace: Summer 2024 <br> <br>

### [**San Diego State University**]{.underline}

#### ***Department of International Security and Conflict Resolution (ISCOR)***

##### [*Teaching Assistant*]{.underline}

-   ISCOR 200 Introduction to ISCOR

    -   G. Allen Greb: Fall 2016, Fall 2014

-   ISCOR 300 Global Systems

    -   G. Allen Greb: Spring 2015

-   ISCOR 310 Our Global Future: Values for Survival

    -   David Larom: Spring 2017

-   ISCOR 320 International Security in the Nuclear Age

    -   G. Allen Greb: Spring 2018, Fall 2017, Spring 2017, Spring 2016, Fall 2015, Spring 2014, Spring 2013 <br> <br>

#### ***Department of Political Science***

##### [*Teaching Assistant*]{.underline}

-   POLS 101 Introduction to American Politics in a Global Perspective

    -   J.T. Smith: Fall 2017, Spring 2017

    -   John Mercurio: Spring 2017, Fall 2016

-   POLS 102 Introduction to American and California Government and Politics

    -   J.T. Smith: Spring 2018, Fall 2017

    -   John Mercurio: Spring 2017, Fall 2016, Spring 2016, Fall 2015

    -   Carole Kennedy: Spring 2016, Fall 2015

-   POLS 375 International Relations

    -   G. Allen Greb: Fall 2013, Fall 2012
